# Generated by Django 4.2.11 on 2024-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='available_join',
            field=models.DateField(null=True),
        ),
    ]
